/// My awesome fact table!
table Fact
	lineageTag: 8238bf5c-6975-43ae-88f4-03a4505049ed

	measure PlaceholderMeasure = SUM(Fact[Revenue]) * 1.1
		lineageTag: 837e6c2e-b4b2-4514-90c4-ef1521344dd5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation Description = "A simple placeholder measure that returns 1.0 for testing purposes"

	/// Calculates the total revenue by summing all revenue values in the Fact table
	measure 'Total Revenue' = SUM(Fact[Revenue])
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567890

	/// Counts the total number of rows/transactions in the Fact table
	measure 'Transaction Count' = COUNTROWS(Fact)
		formatString: #,0
		lineageTag: 9c83d65e-2dd9-403c-b896-22061a33855c

	column Customer
		dataType: string
		lineageTag: 98d90341-091a-4b29-bcb2-3218aced595e
		summarizeBy: none
		sourceColumn: Customer

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 28317872-58fa-4cd9-8d2c-2baa6cfcf354
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Revenue
		dataType: int64
		formatString: 0
		lineageTag: f377ff90-8858-4a28-8c79-55a5728289f8
		summarizeBy: sum
		sourceColumn: Revenue

		annotation SummarizationSetBy = Automatic

	column 'Gross Profit'
		dataType: int64
		formatString: 0
		lineageTag: 43fc94a9-6ba6-4dfe-a5f6-82c7b43aa679
		summarizeBy: sum
		sourceColumn: Gross Profit

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b7c2043a-b5bd-4fe9-addd-9c9f7bd0990c
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 66f7374b-f2f1-4cb1-b9f0-f53dd7aadf2f
			defaultHierarchy: LocalDateTable_26818a28-2e45-4734-83ad-c32aa92d15d9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Imagine if this was our revenue!
	column IdealRevenueCalcColumn = 'Fact'[Revenue] * 10
		formatString: 0
		lineageTag: 64846daa-e185-45f6-bcc3-417e427e772d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Fact = m
		mode: import
		source =
				let
					Source = Table.FromRows(
						Json.Document(
							Binary.Decompress(
								Binary.FromText(
									"i45WcnRyVtJRcnF1A5KGBgZA0hREGBkYmeoaGAKRUqwOUJWzrytQNMQvBEiaGEBUINQZgdXFAgA=", BinaryEncoding.Base64
								),
								Compression.Deflate
							)
						),
						let
							_t = ((type nullable text) meta [Serialized.Text = true])
						in
							type table [Customer = _t, Product = _t, Revenue = _t, #"Gross Profit" = _t, Date = _t]
					),
					#"Changed Type" = Table.TransformColumnTypes(
						Source,
						{
							{"Customer", type text},
							{"Product", type text},
							{"Revenue", Int64.Type},
							{"Gross Profit", Int64.Type},
							{"Date", type date}
						}
					)
				in
					#"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

